require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ConnectionsController do

  def mock_connection(stubs={})
    @mock_connection ||= mock_model(Connection, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all connections as @connections" do
      Connection.stub(:all) { [mock_connection] }
      get :index
      assigns(:connections).should eq([mock_connection])
    end
  end

  describe "GET show" do
    it "assigns the requested connection as @connection" do
      Connection.stub(:find).with("37") { mock_connection }
      get :show, :id => "37"
      assigns(:connection).should be(mock_connection)
    end
  end

  describe "GET new" do
    it "assigns a new connection as @connection" do
      Connection.stub(:new) { mock_connection }
      get :new
      assigns(:connection).should be(mock_connection)
    end
  end

  describe "GET edit" do
    it "assigns the requested connection as @connection" do
      Connection.stub(:find).with("37") { mock_connection }
      get :edit, :id => "37"
      assigns(:connection).should be(mock_connection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created connection as @connection" do
        Connection.stub(:new).with({'these' => 'params'}) { mock_connection(:save => true) }
        post :create, :connection => {'these' => 'params'}
        assigns(:connection).should be(mock_connection)
      end

      it "redirects to the created connection" do
        Connection.stub(:new) { mock_connection(:save => true) }
        post :create, :connection => {}
        response.should redirect_to(connection_url(mock_connection))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved connection as @connection" do
        Connection.stub(:new).with({'these' => 'params'}) { mock_connection(:save => false) }
        post :create, :connection => {'these' => 'params'}
        assigns(:connection).should be(mock_connection)
      end

      it "re-renders the 'new' template" do
        Connection.stub(:new) { mock_connection(:save => false) }
        post :create, :connection => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested connection" do
        Connection.stub(:find).with("37") { mock_connection }
        mock_connection.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :connection => {'these' => 'params'}
      end

      it "assigns the requested connection as @connection" do
        Connection.stub(:find) { mock_connection(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:connection).should be(mock_connection)
      end

      it "redirects to the connection" do
        Connection.stub(:find) { mock_connection(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(connection_url(mock_connection))
      end
    end

    describe "with invalid params" do
      it "assigns the connection as @connection" do
        Connection.stub(:find) { mock_connection(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:connection).should be(mock_connection)
      end

      it "re-renders the 'edit' template" do
        Connection.stub(:find) { mock_connection(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested connection" do
      Connection.stub(:find).with("37") { mock_connection }
      mock_connection.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the connections list" do
      Connection.stub(:find) { mock_connection }
      delete :destroy, :id => "1"
      response.should redirect_to(connections_url)
    end
  end

end
